const types_of_items = [
    'Mechanical Hardware',
    'Electronic Hardware',
    'Electrical Hardware',
    'Peripheral Hardware',
    'Computer Hardware',
    'Computer Related Hardware',
    'Electricity Bill',
    'Office Rent',
    'Vehicle Accessories',
    'Software Renewal (Slack)',
    'Software Renewal (Zoho)',
    'Software Renewal (GoDaddy)',
    'Software Renewal (Indeed)',
    'Software Renewal (Adobe AfterEffects)',
    'BroadBand Connection-1',
    'BroadBand Connection-2',
    'BroadBand Connection-3',
    'Courier Service',
    'Subscription',
    'Vehicle Servicing - Bolero',
    'Vehicle Servicing - Thar',
    'Vehicle Servicing - Fortuner',
    'Car Accessories',
    'Car Repair & Maintenance (Bolero)',
    'Car Repair & Maintenance (Thar)',
    'Car Repair & Maintenance (Fortuner)',
    'Engineering Service',
    'Video Shoot Service(Drone,camera etc)',
    'AC Servicing',
    'Audit Fee',
    'Insurance Premium (Bolero)',
    'Insurance Premium (Thar)',
    'Insurance Premium (Fortuner)',
    'Office Furniture',
    'Battery or Battery Related Service/Purchase',
    'TDS & ROC Compliance Fees'

]

module.exports = types_of_items;